# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b58224f2152945f8fd21f4b9ddbee213bf3765741b6f8f59c4a908101c3118ad6f7357bb88adcbe7c342da4e9dec899de560c85d81d8e76bf51ba0f9115214e

test:
  secret_key_base: f5f66f85f1e960450b5d43d591913f7362aa7f07e4fa701fd0f307aaee1b98707d76ee260630f9bd502db06ebcfc3bfa9a783bd9919cf5484e12a129b2617f0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
